site_name: DeskPRO React SDK
theme_dir: docs/psinder
site_favicon: favicon.png
extra_css:
  - "css/site.css"
repo_name: "GitHub"
repo_url: "https://github.com/DeskproApps/sdk-react"
copyright: "Copyright 2001 – 2017 Deskpro Ltd. All rights reserved."
pages:
  - Overview:  "index.md"
  - Manifest: "pages/manifest.md"
  - Props: "pages/props.md"
  - Components:
    - DeskproSDK: "pages/components/DeskproSDK.md"
    - Routes:     "pages/components/Routes.md"
    - Link:       "pages/components/Link.md"
    - LinkButton: "pages/components/LinkButton.md"
    - Forms:      "pages/components/forms.md"
  - Tutorials:
    - Basic: "pages/tutorials/basic.md"
    - Using Redux: "pages/tutorials/redux.md"
  - API:
    - Actions: "pages/api/actions.md"
